name: Discord send

on:
  push:
    branches:
      - master

jobs:
  message-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          run_url: "https://github.com/jensim/test_discord_action/actions/runs/${{ github.run_id }}"
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub dependency audit
        uses: Ilshidur/action-discord@f237343
        with:
          args: "Dependency security audit failed.\n${{ env.run_url }}"
