name: Discord send

on:
  push:
    branches:
      - master
jobs:
  security_audit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Discord notification
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub dependency audit
        uses: Ilshidur/action-discord@master
        with:
          args: 'Dependency security audit failed.'
