name: Discord send

on:
  push:
    branches:
      - master
env:
  run_url: "https://github.com/jensim/test_discord_action/actions/runs/${{ env.GITHUB_RUN_ID }}"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: GitHub dependency audit
        uses: Ilshidur/action-discord@f237343
        with:
          args: "Dependency security audit failed.\n${{ env.run_url }}"
